import "./globals.css";
import { Assistant } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import GlobalProvider from "@/components/Application/GlobalProvider";

const assistant = Assistant({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || "https://panda-bees.vercel.app/"),
  title: "NextJs Ecom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${assistant.className} antialiased`}>
        <GlobalProvider>
          {children}
          <Toaster />
        </GlobalProvider>
      </body>
    </html>
  );
}
